Updates to half and third width link blob documentation
cfpb/design-manual pull request #444
Opened 2016-12-07 19:17 UTC by nataliafitzgerald

The addition of documentation for the half width and third width link blobs is needed so that Wagtail users are aware of content strategy and design considerations.

## Additions
* Content updates to half width link blob page
* Creation of third width link blob page

## Review
@vczosek 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots
![screencapture-nataliafitzgerald-github-io-design-manual-page-components-half-width-link-blob-html-1481137978773](https://cloud.githubusercontent.com/assets/6887128/20982611/5572ae08-bc87-11e6-98b0-f542d0588b0a.png)
![screencapture-nataliafitzgerald-github-io-design-manual-page-components-third-width-link-blob-html-1481137937725](https://cloud.githubusercontent.com/assets/6887128/20982615/5b3abe3e-bc87-11e6-9bfb-c799d4e75524.png)

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

2017-01-09 16:27 UTC, virginiacc requested changes
@nataliafitzgerald This looks good to me! I just had a few small suggestions for the links/images...

2017-01-09 16:27 UTC, virginiacc commented on page-components/half-width-link-blob.md
> +- When content requires imagery. Suggest using the [50/50 image and text]({{site.baseurl}}//page-components/50-50.html) or [25/75 image and text]({{site.baseurl}}//page-components/25-75.html) compone
It looks like there's an extra slash after `{{site.baseurl}}` in these links (and the ones on the third-width page.)

2017-01-09 16:27 UTC, virginiacc commented on page-components/third-width-link-blob.md
> +<img src="https://raw.githubusercontent.com/nataliafitzgerald/design-manual/gh-pages/static/img/third_width_link_blob/third_width_link_blob_intro.png" alt="Mockup" height="100%" width="100%">
We can use internal paths for the added images:
```
<img src="{{site.baseurl}}/static/img/third_width_link_blob/third_width_link_blob_behavior_1.png" ...>
```

2017-01-12 21:47 UTC, jimmynotjim commented on page-components/half-width-link-blob.md
> +- When content requires imagery. Suggest using the [50/50 image and text]({{site.baseurl}}//page-components/50-50.html) or [25/75 image and text]({{site.baseurl}}//page-components/25-75.html) compone
This seems to be happening throughout this pull request.

2017-01-17 23:59 UTC, nataliafitzgerald commented
@virginiacc @jimmynotjim 
I made some updates to my file to reflect the comments above. Let me know if there is anything else I need to do to share this out. Still learning the process. Thanks!

2017-01-18 15:55 UTC, jimmynotjim commented
@nataliafitzgerald awesome, this is working locally so I'll fix the conflicts and get it merged. Thanks for getting it updated.

2017-01-18 15:57 UTC, merged

2017-01-18 17:53 UTC, nataliafitzgerald commented
@bartonw 
This documentation is finally wrapped up and live on the CFPB Design Manual.