Update to Cf v4
cfpb/design-manual pull request #466
Opened 2017-03-23 14:49 UTC by jimmynotjim

Updated the project to use the latest version of Capital Framework.

## Additions

- Added new color variables from Capital Framework

## Removals

- Removed duplicate styles that have already been ported from cf-enhancements

## Changes

- Updated the CF modules to version 4.1.0 in package.json.
- Updated all the elements to use the correct class names.

## Testing

- run `grunt less && grunt scripts`.
- run `npm start` and navigate through the site.

## Review

- @Scotchester  
- @cfarm 
- @contolini 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

## Notes

- There are a few color variable that aren't using colors from our palette. I'm leaving them as is for now because they should really be handled in the cfpb-theme.

## Todos

- Remove any duplicate styles between this project and Capital Framework.
- Update the project to use the cfpb-theme module.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

2017-03-23 19:19 UTC, Scotchester commented
This is not a problem with your PR, but looking at the expandables page, I realize that our `:last-child { margin-bottom: 0; }` rule has eliminated the bottom spacing in all expandables, which were counting on their last child's bottom margin to be there. I'll file an issue in capital-framework.

2017-03-23 19:51 UTC, Scotchester commented
Got a couple issues on the Tables page:

<img width="871" alt="screen shot 2017-03-23 at 15 50 02" src="https://cloud.githubusercontent.com/assets/1044670/24267380/7b19928c-0fe0-11e7-9be2-e026f9589cd8.png">

<img width="897" alt="screen shot 2017-03-23 at 15 50 22" src="https://cloud.githubusercontent.com/assets/1044670/24267394/8199390a-0fe0-11e7-8e66-8a6aec6b3c27.png">

2017-03-31 21:48 UTC, jimmynotjim commented
Updated with @Scotchester fix for pagination and markup corrections for the tables. I removed the 100% inline widths because I'd like to solve that issue in cf-tables. I don't know if we should hold this up for that or not though.

2017-04-10 21:32 UTC, jimmynotjim commented
It's going to get messy dealing with ongoing changes to the less files with this project on v3. Can we merge this?

2017-04-11 22:45 UTC, Scotchester commented
Testing this again locally.

> I removed the 100% inline widths because I'd like to solve that issue in cf-tables.

Are you proposing we set all table widths to 100% by default? I'm not sure we want to do that.

But anyway, a more efficient way to do it in this project would be to add a style for it in the project's stylesheets. I'll commit that, along with a fix for the pagination style to correctly show how it would look on a small screen.

We should also decide whether the expandable bottom padding issue should be a blocker to moving forward with this. As soon as we publish, those examples will look broken.

2017-04-12 16:39 UTC, jimmynotjim commented
@Scotchester agreed that the best option would be setting them in the main stylesheet of this project. As far as the expandables, yes, we should fix that first. I can do that after I make the hero updates today.

2017-04-12 17:25 UTC, Scotchester commented
Whoops, pushed that commit to my fork yesterday afternoon. Pushed it here now.

2017-04-12 18:00 UTC, jimmynotjim commented on Gruntfile.js
> +        files: ['index.html', '**/*.md'],
Why are we even converting these? Let's let Jekyll handle the markdown files, just like we did on the CF docs site.

2017-04-12 18:01 UTC, jimmynotjim commented on src/static/css/content.less
> +// Display pagination examples in half columns as their mobile view
I still need to try the iframe suggestion @niqjohnson had. Maybe I can find time on Friday.

2017-04-12 18:11 UTC, Scotchester commented on Gruntfile.js
> +        files: ['index.html', '**/*.md'],
They're not being converted, just triggering the copy task. The main use case would be adding new images to a page. On saving the MD file, images will be recopied from `./src/static/img/` (everything in `src` is ignored by Jekyll) to `./static/img`, where they'll be picked up by Jekyll's watcher.

We could consider altering/getting rid of the `src`/"`dist`" model that's in use here and just keep static files that need no building in `./static`.

2017-04-21 20:00 UTC, jimmynotjim commented
Expandables bug is being addressed at https://github.com/cfpb/AtomicComponent/pull/4 and https://github.com/cfpb/capital-framework/pull/471

2017-04-24 22:00 UTC, jimmynotjim commented
@Scotchester I think I've addressed everything we discovered in this process. Hopefully we can merge this and keep moving on other improvements.

2017-04-27 16:38 UTC, Scotchester requested changes
Need a quick update to the `package.json` file to make sure I'm testing things totally cleanly, rather than relying on npm links.

2017-04-27 16:38 UTC, Scotchester commented on Gemfile.lock
> +GEM
How about we go ahead and remove & ignore `Gemfile.lock`?

2017-04-27 16:38 UTC, Scotchester commented on package.json
> +    "cf-typography": "^4.1.0",
Several of these need to get updated to their latest releases. Easiest thing to reference is the badges at the top of the capital-framework README.

2017-04-27 17:16 UTC, jimmynotjim commented on package.json
> +    "cf-typography": "^4.1.0",
@Scotchester the `^` takes care of that for you, run `npm update`.

2017-04-27 17:19 UTC, jimmynotjim commented on Gemfile.lock
> +GEM
That will go away when I rebase, @marteki removed that already.

2017-04-27 18:21 UTC, Scotchester approved these changes

2017-04-27 18:21 UTC, Scotchester commented
:+1:

2017-04-27 18:24 UTC, merged