Updated the gitignore to match Capital Framework gh-pages
cfpb/design-manual pull request #484
Opened 2017-04-27 17:20 UTC by jimmynotjim

Matching Capital Framework with the current best version of `.gitignore` for Jekyll projects.

2017-04-27 18:00 UTC, marteki requested changes
I added one disagreement with a line removal, and one question about another line removal. I agree with the general idea of updating to match across Capital Framework and the Design Manual!

2017-04-27 18:00 UTC, marteki commented on .gitignore
> -Gemfile.lock
I've had issues in the past on this repo when I came back to it after a while, but my `Gemfile.lock` file was old and out of date. It was keeping me pegged to several versions behind on gems.

2017-04-27 18:00 UTC, marteki commented on .gitignore
> -src/static/fonts/
Do we want to have `src/static/fonts/` tracked in Git?

2017-04-27 18:10 UTC, jimmynotjim commented on .gitignore
> -src/static/fonts/
This doesn't exist, the fonts are in `static/fonts`, no `src/`

2017-04-27 18:13 UTC, jimmynotjim commented on .gitignore
> -Gemfile.lock
That was a mistake, updated with the correct settings and it's been moved under the `Jekyll` heading.

2017-04-27 18:26 UTC, Scotchester approved these changes
:+1:

2017-04-27 21:16 UTC, marteki approved these changes

2017-04-27 21:52 UTC, merged

2017-04-28 17:44 UTC, Scotchester commented on .gitignore
> -src/static/fonts/
You were incorrect about that. They start in `src/static/fonts` and get copied to `static/fonts`. That said, they should _really_ be originating from `node_modules/cf-icons/src/fonts`.

2017-04-28 17:50 UTC, jimmynotjim commented on .gitignore
> -src/static/fonts/
@Scotchester I don't have them in my `/src/static/fonts`, am I missing something?

2017-04-28 17:59 UTC, Scotchester commented on .gitignore
> -src/static/fonts/
I have them locally there. Not sure why they got removed from that location/ignored. I'll look back at the `.gitignore` blame in a sec. But if you look at `grunt:copy`, that was the original intent.

2017-04-28 18:01 UTC, jimmynotjim commented on .gitignore
> -src/static/fonts/
Yeah, I saw that too. I think what happened was we stopped installing from bower to `/src`, but never updated the tasks to match. That said, we could really use a clean up of the tasks and should probably port them to Gulp so we're consistent with other projects. What say you?

2017-04-28 18:02 UTC, Scotchester commented on .gitignore
> -src/static/fonts/
[I did it.](https://github.com/cfpb/design-manual/commit/c303bf93a34f3d45023e8a84a5b514eacf64500c) _( 🎶 Do you think I've gone too far?)_

Not sure why. Anyway, I'll fix it by bringing them in from cf-icons.

2017-04-28 18:03 UTC, Scotchester commented on .gitignore
> -src/static/fonts/
Ah yeah, it probably was the deprecation of Bower.

2017-04-28 18:06 UTC, jimmynotjim commented on .gitignore
> -src/static/fonts/
Ok, delete that dir from your local before you check them in accidentally ;)